version: "2"
services:
  api:
    build: ./food_finder_api
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/ftf_api

  client:
    build: ./food_finder_client
    ports:
      - "80:80"
    depends_on:
      - api
